export const SET_OPEN_LOGIN_DIALOG = 'setOpenLoginDialog'
export const SET_OPEN_LOGIN_ADMIN_DIALOG = 'setOpenLoginAdminDialog'
export const OPEN_LOGIN_DIALOG = 'openLoginDialog'
export const OPEN_LOGIN_ADMIN_DIALOG = 'openLoginAdminDialog'
export const CHANGE_COUNTRY = 'countryChange'
export const IS_LOGGED_IN = 'isLoggedIn'
